baseurl = "http://mragsac.github.io"
title = "Michelle Ragsac"
# the number of posts on a page
paginate = 10

# theme:
# https://github.com/mpas/hugo-multi-bootswatch

publishdir = "public"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:title/"

[author]
    # Optional. Used in RSS feed meta information.
    name = "Michelle Ragsac"
    email = "michelle.ragsac@gmail.com"

[params]
    # language code for your website
    languagecode = "en-US"

    # name of the site author; used in header meta information
    author = "Michelle Ragsac"

    # copyright text; used in footer
    copyright = "2016 Michelle Ragsac"

    # social links, used in footer, these must be full URLs.
    # twitter     = "https://twitter.com/<username>"
    github      = "https://github.com/mragsac"
    # facebook    = "https://www.facebook.com/<username>"
    # delicious   = "https://delicious.com/<username>"
    linkedin    = "https://www.linkedin.com/in/michelleragsac"
    # flickr      = "https://www.flickr.com/photos/<username>"

    # show default summaries on the frontpage or not
    use_summaries = true

# naming of the elements in your blog/site
[params.strings]
    # name of the link to the homepage
    home_navbar_link = "Home"

    # name of the link to the blog page
    blog_navbar_link = "Posts"

    # used date format
    # month.date.year
    date_format = '01.02.2006'

# aditional menu items
[menu]
    [[menu.main]]
    # about page
    identifier = "about"
    name = "About"
    url = "/page/about"
    weight = 0

    [[menu.main]]
    # links to resume
    identifier = "resume"
    name = "Resume"
    url = "http://mragsac.github.io/docs/michelleRagsac_resume.pdf"
    weight = 1

[params.theme]
    inverse = false     # indicating if the theme should use inversed colors
    name = "cosmo"   # name of the theme to use

    # list of possible theme names that can be used
    # name = "cerulean"
    # name = "cosmo"
    # name = "cyborg"
    # name = "default"
    # name = "flatly"
    # name = "journal"
    # name = "lumen"
    # name = "paper"
    # name = "readable"
    # name = "sandstone"
    # name = "simplex"
    # name = "slate"
    # name = "spacelabs"
    # name = "superhero"
    # name = "united"
    # name = "yeti"