#!/bin/bash

# changes into the correct directory
cd ~/Desktop/blog-hugo/

# runs the server command to show the site at localhost:1313
open http://localhost:1313/
hugo server --theme=hugo-multi-bootswatch 